# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-22 02:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('creation_date', models.DateField(verbose_name='Event Creation Date')),
                ('address', models.CharField(blank=True, max_length=45, null=True, verbose_name='Address')),
                ('address2', models.CharField(blank=True, max_length=45, null=True, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=45, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=45, null=True, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zipcode')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Event Date')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Events',
                'get_latest_by': 'creation_datetime',
                'db_table': 'event',
            },
        ),
    ]
