FROM python:3.5
ENV PYTHONUNBUFFERED 1

COPY requirements/base.txt /home/docker/requirements-base.txt
COPY requirements/local.txt /home/docker/requirements-local.txt
COPY requirements/test.txt /home/docker/requirements-test.txt

RUN pip install -r /home/docker/requirements-base.txt\
    -r /home/docker/requirements-local.txt \
    -r /home/docker/requirements-test.txt

WORKDIR /home/docker/ispa

COPY scripts/start-dev.sh /start-dev.sh

COPY ispa .

ENTRYPOINT ["/start-dev.sh"]
