# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 23:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ispa_app', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Event Date')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('points', models.IntegerField()),
                ('eventtype', models.CharField(choices=[('event', 'Event'), ('meeting', 'Meeting'), ('semester', 'Semester')], default='event', max_length=128)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('guests', modelcluster.fields.ParentalManyToManyField(related_name='events', to='ispa_app.Member')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=45, null=True, verbose_name='Address')),
                ('address2', models.CharField(blank=True, max_length=45, null=True, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=45, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=45, null=True, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zipcode')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventLocation'),
        ),
    ]
