# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 20:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Event Date')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
            ],
            options={
                'db_table': 'event',
                'verbose_name': 'Events',
                'get_latest_by': 'creation_datetime',
            },
        ),
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True, verbose_name='Address')),
                ('address2', models.CharField(blank=True, max_length=45, null=True, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=45, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=45, null=True, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zipcode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventLocation'),
        ),
    ]
