# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventtype',
        ),
    ]
