# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-29 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventguest',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventguest',
            name='guest',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='semester',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='EventGuest',
        ),
    ]
