# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170806_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='event',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('event', 'Event'), ('semester', 'Semester'), ('meeting', 'Meeting')], max_length=128, null=True, verbose_name='Event Type'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
