# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170809_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='points',
        ),
    ]
