# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170809_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attending',
            field=models.BooleanField(default=True),
        ),
    ]
