# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170809_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extended_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
