# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import events.models.speaker


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_extended_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=events.models.speaker.image_field)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
