# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='points',
            field=models.PositiveIntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.PositiveIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
