# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SM', 'Sophmore'), ('JR', 'Junior')], default='FR', max_length=56),
        ),
    ]
