# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20170820_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date',)},
        ),
    ]
