# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20170826_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tshirt',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=56),
        ),
    ]
