# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20170827_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='events',
            new_name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='messages',
            field=models.ManyToManyField(related_name='messages', to='events.Message'),
        ),
    ]
