# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20170828_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
