# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_update_events_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='messages',
        ),
    ]
