# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20170831_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 2, 9, 43, 785489, tzinfo=utc), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 1, 2, 9, 43, 785431, tzinfo=utc), verbose_name='Start date'),
        ),
    ]
