# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-02 00:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20170901_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 3, 0, 48, 48, 41506, tzinfo=utc), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 0, 48, 48, 41444, tzinfo=utc), verbose_name='Start date'),
        ),
    ]
