# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 04:02
from __future__ import unicode_literals

import core.models.sponsors
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.sponsors.image_field)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
