# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 01:18
from __future__ import unicode_literals

import core.models.alumni
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.alumni.image_field)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
                ('extended_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='extended_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
